//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkSomewhere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Park
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Park()
        {
            this.Photos = new HashSet<Photo>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int ParkID { get; set; }
        public string ParkName { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public System.TimeSpan OpenTime { get; set; }
        public System.TimeSpan CloseTime { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> AvgRating { get; set; }
        public Nullable<int> NumberRatings { get; set; }
        public bool RestRooms { get; set; }
        public bool PicnicArea { get; set; }
        public bool Grill { get; set; }
        public bool Playground { get; set; }
        public bool HikingTrail { get; set; }
        public bool PavedTrails { get; set; }
        public bool BasketballCourt { get; set; }
        public bool BaseballDiamond { get; set; }
        public bool CampGround { get; set; }
        public bool Fishing { get; set; }
        public bool Swimming { get; set; }
        public bool FitnessTrails { get; set; }
        public bool ADAAccessible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
